### ISSUE TITLE
document default values

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#20]
It would be helpful if the documentation could also show the default value.

**Comment by BebeSparkelSparkel** [comment]
#22 implementation failed

generating the docs from ProgramT fails because the it is possible to create bad docs because different value can create different ProgramT.

**Comment by BebeSparkelSparkel** [comment]
#21 has a good implementation for this

**Comment by SamuelSchlesinger** [comment]
Yeah, this is a hard problem that I've thought a bit about. It sort of doesn't fit in the design I've chosen. My design gains you some dynamism with the default, but loses documentation. It's not obvious to me which is preferred.

**Comment by SamuelSchlesinger** [comment]
Looking at #21 now.

**Comment by BebeSparkelSparkel** [comment]
Why not have both then? Prefer the way that documents the defaults but allow for the dynamic values if the user requires them.

**Comment by SamuelSchlesinger** [comment]
Yeah, I agree with that tact 👍

**Comment by BebeSparkelSparkel** [comment]
replaced with #40 and #41. Those still need to allow for dynamic values
