### ISSUE TITLE
multiple arguments

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#23]
Many commands have the ability to take multiple arguments like `rm` and `cp`.

```text
rm [-dfiPRrv] file ...
cp [-afipv] [-R [-H | -L | -P]] source ... directory
```

`rm` is the easy case but `cp` is a bit more difficult to parse because it must not consume the last argument `directory`.

**Comment by SamuelSchlesinger** [comment]
Yeah, this is a great idea. I'd take a PR for this, or will perhaps tackle it on my own at some point.

**Comment by BebeSparkelSparkel** [comment]
already have PR for theis #30

**Comment by SamuelSchlesinger** [comment]
Too big for me to review and merge comfortably.
