### ISSUE TITLE
combined flags

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#24]
Allow combined flags like with `ls`

```text
ls [-1AaCcdFfgHhikLlmnopqRrSsTtux] [file ...]
```

Some questions that need answering.
- Is this an anti-pattern, and should it be implemented?
- Should this be limited to single letter flags?
- How should it be implemented?
  - combine flags at the type level and then split the flags on parsing

**Comment by SamuelSchlesinger** [comment]
I'm not sure of how I feel about this. If it can be implemented clearly and well-documented, the more features the better, but if it adds confusion or indirection to the extant code, I will be anti.

**Comment by BebeSparkelSparkel** [comment]
This is a tricky one. I don't really like learning them but as a power user they are very helpful.

**Comment by SamuelSchlesinger** [comment]
Agreed, sadly I think this issue is especially important despite the pain it will likely cause in the implementation.

**Comment by BebeSparkelSparkel** [comment]
Perhaps this isn't as hard you think. This could be implemented as:

```haskell
data Flags
  :: Symbol -- prefix
  -> Symbol -- single letter flags
  -> *
```

then `run` would
- match on the prefix
- ensure all letters are in the single letter flags symbol
- split the letters and prepend the prefix and then prepend those on the State
- the following flag handlers will then consume the indiv

Another option would be:
```haskell
data Flags
  :: Symbol -- prefix
  -> [(Symbol,Symbol)] -- single letter map to flag
  -> *
```

this is a bit more flexible than the previous option that allows for mappings to flags that have more than one letter and allows for a different prefix for combined single letters flags than the other flags.

As for checking this it may be possible for a type function to ensure that there is a flag handler is defined after this.
