### ISSUE TITLE
Standard CLI behavior for toplevel

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#42]
It would be nice to have more standard behavior for `toplevel` that implements what users would expect to have with a toplevel helper cli function.

- show help with `-h`
- show help with `--help`
- show help with no arguments
- show help with parse error
- exit non-zero status with parse error, so that scripts know that command failed

**Comment by SamuelSchlesinger** [comment]
I totally agree with this.
