### ISSUE TITLE
Many new features in fork that you might consider pulling

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#46]
I've added a lot of functionality in my fork.
It's probably a hard fork at this point but you still will probably find some of the features that I have added intriguing.

**Comment by SamuelSchlesinger** [comment]
The main features I want are documenting default values, which I believe you have, and improved documentation (i.e. something closer to what optparse-applicative gives).

Honestly, compiling into an optparse-applicative parser is highly appealing, but this is a very breaking change.
