### ISSUE TITLE
forall to show type argument order

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#6]
Since this is a type argument heavy it would be helpful to have `forall` in the types to see the ordering of the type arguments.

**Comment by SamuelSchlesinger** [comment]
I totally agree with this. Let me know if https://github.com/SamuelSchlesinger/commander-cli/pull/8 is sufficient.

**Comment by BebeSparkelSparkel** [comment]
Not sure what is happening in a lot of the files. Where the foralls are being added is what I was looking for.

**Comment by BebeSparkelSparkel** [comment]
closed by #8
