### ISSUE TITLE
show example in function documentation

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#7]
It would be very helpful to have an example argument in the function descriptions.

example: argument
```text
commandName arumentValue
```

example: keyed argument
```text
commandName -key value
```

**Comment by SamuelSchlesinger** [comment]
Oh I'm sorry, I just saw this. I'm not sure if I understand what you mean.. Can you elaborate?

**Comment by BebeSparkelSparkel** [comment]
Sure

```text
arg :: KnownSymbol name => (x -> ProgramT p m a) -> ProgramT (Arg name x & p) m a
someCommand someArgument
            ^^^arg value^^^

opt :: (KnownSymbol option, KnownSymbol name) => (Maybe x -> ProgramT p m a) -> ProgramT (Opt option name x & p) m a
someCommand -option optionValue
            ^^option^^ ^^option value ^^
only one dash before the option with the a space between it and its value
```

Enough to describe the command line syntax. Right now it is some what hard to tell what the combinator CLI syntax is.

**Comment by SamuelSchlesinger** [comment]
Ah, now I understand. If you have a particular idea in mind, please feel free to PR it, otherwise I'll get to it sometime.
