### ISSUE TITLE
Example Rendered Incorrectly

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander-cli#9]
The rendering of the documentation in [Options.Commander](https://hackage.haskell.org/package/commander-cli-0.10.1.2/docs/Options-Commander.html#t:ProgramT) on hackage causes all the `@` to disappear in the example.
I'm not sure how to fix this, maybe escapes? Or, just move it to the README.

**Comment by SamuelSchlesinger** [comment]
Oh yeah, I saw that... Not quite sure about that, I wonder if that is a haddock bug or I am using haddock improperly.
